project_name: clamp
before:
  hooks:
    - go mod download
    - go generate ./...
release:
  prerelease: false
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  - id: clamp
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew
brews:
  -
    name: clamp
    github:
      owner: JulienBreux
      name: homebrew-clamp
    commit_author:
      name: Julien Breux
      email: julien.breux@gmail.com
    folder: Formula
    homepage: https://julienbreux.github.io/clamp/
    description: Clamp is a useful tool to help to replace environment variables in any file using go template syntax.
    test: |
      system "clamp -v"
