---
project_name: clamp
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/clamp/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/julienbreux/clamp/pkg/version.version={{.Version}} -X github.com/julienbreux/clamp/pkg/version.commit={{.Commit}} -X github.com/julienbreux/clamp/pkg/version.date={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
dockers:
  - image_templates:
      - 'julienbreux/clamp:{{ .Tag }}'
      - 'julienbreux/clamp:latest'
      - 'ghcr.io/julienbreux/clamp:{{ .Tag }}'
      - 'ghcr.io/julienbreux/clamp:latest'
    dockerfile: Containerfile
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.name={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/julienbreux/clamp
      - --label=org.opencontainers.image.source=https://github.com/julienbreux/clamp
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
brews:
  - name: clamp
    tap:
      owner: JulienBreux
      name: homebrew-clamp
    commit_author:
      name: Julien Breux
      email: julien@golang.fr
    folder: Formula
    homepage: https://github.com/julienbreux/clamp/
    description: 🗜 Clamp — Replace environment variables in any file using go template syntax
    test: system "clamp -v"
